# .github/workflows/build_disk.yml
name: Build Leviathan ISO & VM

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'disk_config/**'
      - '.github/workflows/build_disk.yml'

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  DEFAULT_TAG: latest
  BIB_IMAGE: ghcr.io/lorbuschris/bootc-image-builder:20250608

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ISO & QCOW2
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Prepare environment
        shell: bash
        run: |
          set -euxo pipefail
          USER_UID=$(id -u)
          USER_GID=$(id -g)
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME,,}"       >> $GITHUB_ENV
          echo "USER_UID=${USER_UID}"             >> $GITHUB_ENV
          echo "USER_GID=${USER_GID}"             >> $GITHUB_ENV

      - name: Free Runner Space
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get clean
          sudo rm -rf /home/runner/.cache/* /tmp/*
          sudo rm -rf /var/lib/containers/storage/*

      - name: Show pre-build disk usage
        shell: bash
        run: |
          set -euxo pipefail
          echo "=== df -h / ==="
          df -h /
          echo "=== df -h /home ==="
          df -h /home
          echo "=== lsblk ==="
          lsblk
          echo "=== du -sh /var/lib/containers/storage ==="
          du -sh /var/lib/containers/storage || true

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e
        with:
          remove-codeql: true

      - name: Build ISO image
        id: build_iso
        uses: osbuild/bootc-image-builder-action@main
        with:
          builder-image: ${{ env.BIB_IMAGE }}
          config-file: ./disk_config/disk.toml
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DEFAULT_TAG }}
          chown: ${{ env.USER_UID }}:${{ env.USER_GID }}
          types: anaconda-iso
          additional-args: "--use-librepo=True --log-level debug"

      - name: Build QCOW2 disk image
        id: build_qcow2
        uses: osbuild/bootc-image-builder-action@main
        with:
          builder-image: ${{ env.BIB_IMAGE }}
          config-file: ./disk_config/disk.toml
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DEFAULT_TAG }}
          chown: ${{ env.USER_UID }}:${{ env.USER_GID }}
          types: qcow2
          rootfs: ext4
          additional-args: "--use-librepo=True --log-level debug"

      - name: Upload disk artifacts
        uses: actions/upload-artifact@v4
        with:
          name: disk-artifacts
          path: ${{ steps.build_qcow2.outputs.output-directory }}
          if-no-files-found: error
          retention-days: 30
          overwrite: true
