# .github/workflows/list-installed-components.yml
name: List Installed Components

on:
  workflow_dispatch:

jobs:
  list:
    name: List Installed Components
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/large-farva/leviathan:latest
      # omit credentials if the image is public

    steps:
      - name: Install jq
        run: |
          dnf install -y jq

      - name: List RPM packages
        run: |
          rpm -qa --qf '%{NAME}-%{VERSION}-%{RELEASE}\n' \
            | sort > dnf-packages.txt

      - name: List rpm-ostree layered packages
        run: |
          rpm-ostree status --json \
            | jq -r '.deployments[0].layeredPackages[]?' \
            | sort > ostree-layered-packages.txt

      - name: List Flatpak apps
        run: |
          flatpak list --system --app --columns=application \
            | sort > flatpaks.txt

      - name: List system GNOME Shell extensions
        run: |
          ls /usr/share/gnome-shell/extensions \
            | sort > gnome-extensions.txt

      - name: Upload all lists
        uses: actions/upload-artifact@v4
        with:
          name: installed-components
          path: |
            dnf-packages.txt
            ostree-layered-packages.txt
            flatpaks.txt
            gnome-extensions.txt
