# .github/workflows/list-installed-components.yml
name: List Installed Components

on:
  workflow_dispatch:

jobs:
  list:
    name: List Installed Components
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ublue-os/bazzite-gnome-nvidia:latest

    steps:
      - name: List all RPM packages
        run: |
          rpm -qa --qf '%{NAME}-%{VERSION}-%{RELEASE}\n' \
            | sort > rpm-packages.txt

      - name: List rpm-ostree layered packages
        run: |
          rpm-ostree status \
            | sed -n '/LayeredPackages:/,/^$/p' \
            | tail -n +2 \
            | sed 's/^[[:space:]]*//' \
            | sort > ostree-layered-packages.txt

      - name: List Flatpak apps
        run: |
          flatpak list --app --columns=application \
            | sort > flatpaks.txt

      - name: List enabled GNOME Shell extensions
        run: |
          dconf read /org/gnome/shell/enabled-extensions \
            | sed "s/[][]//g; s/'//g; s/,/\\n/g" \
            | sed '/^\s*$/d' \
            | sort > gnome-extensions.txt

      - name: Upload all lists as artifact
        uses: actions/upload-artifact@v4
        with:
          name: installed-lists
          path: |
            rpm-packages.txt
            ostree-layered-packages.txt
            flatpaks.txt
            gnome-extensions.txt
